Improve testing documentation#6
mild-blue/breviary-documentation pull request #10
Opened 2022-10-21 09:39 UTC by anhelina-sadovnikova

…dding new test result

2022-10-24 13:00 UTC, kubantjan requested changes
Takhle flat ta struktura je hoodne neprehledna, chtelo by to rozhodit do slozky heparin a inzulin minimalne. Asi idealne bych ale pak nedelal tak moc ruznych filu, ale trosku to dal vic pokupe.

jinak mi to prijde fajn

2022-10-24 13:06 UTC, kubantjan requested changes

2022-10-24 13:06 UTC, kubantjan commented on frontend/getting_ready.md
> +### iOS instalace beta-verze
Tento file bych prejmenoval na README.

a napsal bych sem neco jako

toto jsou podklady pro testovani aplikace brviary. n

nize je popis pro pripravu prostredi a pak rozcestnik na jednotlive testovaci scenare.

Pokud chcete pridat novy scenar tak bla bla

2022-10-25 13:15 UTC, kubantjan commented
@anhelina-sadovnikova  pripominam code style best practices, ty commit message moc neodpovidaji :) (viz https://github.com/mild-blue/knowledge-base/tree/master/code )

2022-10-25 13:17 UTC, kubantjan requested changes
Tak jen prosim upravit ty commit messages.

Plus odpoved na otakzu, vsechny ty scenare co tu jsou jsou otestovany a funguje to presne tak, jak tam pises jo?

2022-10-25 14:06 UTC, anhelina-sadovnikova commented
> Ano, jsou otestovany a funguji

2022-10-26 10:09 UTC, kubantjan approved these changes

2022-10-26 10:10 UTC, merged